# Generated by Django 3.0 on 2019-12-13 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='razao',
            new_name='corporate_name',
        ),
    ]
