# Generated by Django 3.0 on 2019-12-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_auto_20191213_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
