# Generated by Django 3.0 on 2019-12-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('razao', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=11)),
                ('fone', models.CharField(max_length=11)),
                ('public_place', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
