# Generated by Django 3.0 on 2019-12-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantidade',
            new_name='amount',
        ),
    ]
