# Generated by Django 3.0 on 2019-12-13 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0003_auto_20191213_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('buy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField(auto_now=True)),
                ('suppliers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.Suppliers')),
            ],
        ),
    ]
